FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src /app/src

COPY src/EasyOCR/model/craft_mlt_25k.pth /root/.EasyOCR/model/craft_mlt_25k.pth
COPY src/EasyOCR/model/english_g2.pth /root/.EasyOCR/model/english_g2.python

# Set environment variable to include /app/src in PYTHONPATH
ENV PYTHONPATH="${PYTHONPATH}:/app/src"

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]