version: "3.9"

services:
  app:
    build: .
    network_mode: "host"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:mysql1234@127.0.0.1:3306/test_login
    depends_on:
      - cloudsql-proxy

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    container_name: cloudsql-proxy
    restart: always
    network_mode: "host"
    command: /cloud_sql_proxy -instances=servertest-425513:us-central1:mysql-test=tcp:3306 -credential_file=/secrets/cloudsql/credentials.json
    volumes:
      - /home/wkdrjsdl12/TodoApp/servertest-425513-ab5dd4787884.json:/secrets/cloudsql/credentials.json
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "3306"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"   
    # - "443:443"
    # environment:
    #   - CERTBOT_EMAIL=youremail@gmail.com
    volumes:
      - /home/wkdrjsdl12/TodoApp/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

volumes:
  db-data: