from auth.config import settings

SECRET_KEY = settings.SECRET_KEY
ALGORITHM = settings.ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7
# SMS_KEY="66ca6ecb"
# SMS_SECRET_KEY = "zf7i6lMwv1E3Arny"